---
- name: taiga-nginx
  hosts: "{{ deploy_hosts }}"
  gather_facts: no
  vars:
     server_type: "taiga"
  vars_files:
    - group_vars/postgres_taiga
    - group_vars/rabbitmq_taiga
    - group_vars/taiga_back
  roles:
    - nginx
