---
- name: Install postgresql, Add database and user
  hosts: "{{ deploy_hosts }}"
  gather_facts: no
  become: true
  become_user: postgres
  vars_files:
    - group_vars/postgres_taiga
  roles:
    - postgres
