- name: pre-install nodejs
  become: true
  become_user: root
  # shell: curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
  shell: curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -

- name: "Run the equivalent of 'apt-get update' as a separate step"
  become: true
  apt:
    update_cache: yes

- name: install nodejs
  #apt: pkg={{ item }} state=present
  apt: pkg=nodejs state=present
  become: true
  become_user: root

- name: npm config set registry https://registry.npm.taobao.org
  become: true
  become_user: taiga
  shell: npm config set registry https://registry.npm.taobao.org

- name: install the javascript dependencies needed
  become: true
  become_user: taiga
  shell: npm install
  args:
    chdir: /home/taiga/taiga-events-master

- name: copy config.json taiga-back-stable/config.json
  become: true
  become_user: taiga
  template:
    src: config.json
    dest: /home/taiga/taiga-events-master/config.json
    owner: taiga
    group: taiga
    mode: 0644
