---
# install nodejs (method 2)
- name: install nodejs from aliyun
  become: true
  become_user: root
  unarchive:
    src: https://npm.taobao.org/mirrors/node/v10.15.3/node-v10.15.3-linux-x64.tar.xz
    dest: /usr/local/
    # /usr/local/node-v10.15.3-linux-x64
    remote_src: yes

- name: link node -> /usr/bin/
  become: true
  become_user: root
  file:
    src: '/usr/local/node-v10.15.3-linux-x64/bin/{{ item.src }}'
    dest: '/usr/local/bin/{{ item.dest }}'
    state: link
  with_items:
    - { src: 'node', dest: 'node' }
    - { src: 'npm', dest: 'npm' }
    - { src: 'npx', dest: 'npx' }

- name: npm config set registry https://registry.npm.taobao.org
  become: true
  become_user: taiga
  shell: npm config set registry https://registry.npm.taobao.org

- name: install the javascript dependencies needed
  become: true
  become_user: taiga
  shell: npm install
  args:
    chdir: /home/taiga/taiga-events-master

- name: copy config.json taiga-back-stable/config.json
  become: true
  become_user: taiga
  template:
    src: config.json
    dest: /home/taiga/taiga-events-master/config.json
    owner: taiga
    group: taiga
    mode: 0644
