- name: "change repo to china-tuna"
  copy:
    src: ubuntu-16.04-tsinghua.sources.list
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: 0644
    backup: yes

- name: "Run the equivalent of 'apt-get update' as a separate step"
  become: true
  apt:
    update_cache: yes
