- name: Install postgresql_db1
  postgresql_db:
    name: "{{ postgresql_db1_name }}"
    encoding: UTF-8
    #lc_collate: zh_CN.UTF-8
    #lc_ctype: zh_cn.UTF-8
    template: template0

- name: Install postgresql_db
  postgresql_db:
    name: "{{ postgresql_db_name }}"
    encoding: UTF-8
    #lc_collate: zh_CN.UTF-8
    #lc_ctype: zh_cn.UTF-8
    template: template0
